# Generated by Django 3.2.7 on 2021-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('isbn', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
